### ISSUE TITLE
Setup yaml files & Start Up Not working

### ISSUE THREAD

**Issue by ongraiso** [mlundine/Shoreline_Extraction_GAN#1]
I have setup the env files according to the yaml files some and some libs can't be installed to work normally, and when I using vscode excute this program. there is a problem.

(shoreline_gan)C:\Users\15595\Desktop\extract\Shoreline_Extraction_GAN_release\Shoreline_Extraction_GAN>python shoreline_gan_gui.py                              
Traceback (most recent call last):
  File "C:\Users\15595\.conda\envs\shoreline_gan\lib\site-packages\osgeo\__init__.py", line 29, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\15595\.conda\envs\shoreline_gan\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: 找不到指定的模块。

Traceback (most recent call last):
  File "shoreline_gan_gui.py", line 19, in <module>
    from utils import download_utils
  File "C:\Users\15595\Desktop\extract\Shoreline_Extraction_GAN_release\Shoreline_Extraction_GAN\utils\download_utils.py", line 10, in <module>    import gdal_functions_app as gda
  File "C:\Users\15595\Desktop\extract\Shoreline_Extraction_GAN_release\Shoreline_Extraction_GAN\utils\gdal_modules\gdal_functions_app.py", line 8, in <module>       from osgeo import gdal, ogr, osr
  File "C:\Users\15595\.conda\envs\shoreline_gan\lib\site-packages\osgeo\__init__.py", line 45, in <module>    _gdal = swig_import_helper()
  File "C:\Users\15595\.conda\envs\shoreline_gan\lib\site-packages\osgeo\__init__.py", line 42, in swig_import_helper    return importlib.import_module('_gdal')
  File "C:\Users\15595\.conda\envs\shoreline_gan\lib\importlib\__init__.py", line 127, in import_module    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_gdal'

(shoreline_gan)C:\Users\15595\Desktop\extract\Shoreline_Extraction_GAN_release\Shoreline_Extraction_GAN>

**Comment by mlundine** [comment]
Looks like gdal didn't install correctly. Try manually installing it into the shoreline_gan environment with conda.

`conda install gdal`

**Comment by ongraiso** [comment]
Thank you. It is true that the gdal could not be installed correctly. The problem is solved
