### ISSUE TITLE
Problem with shoreline extraction

### ISSUE THREAD

**Issue by VuHoangDao** [mlundine/Shoreline_Extraction_GAN#2]
Your model makes me impressive and I try to run our model. So I have 2 questions:
1. I also make a shapefile for my case study area but I can't download images by that shapefile. So, I use coordinate as your guidance.
2. I get disconnected from the model When I run the shoreline Extraction tool while setting up my data as your guidance.

![image](https://github.com/mlundine/Shoreline_Extraction_GAN/assets/112917719/98277c55-601c-4739-bd7f-b417186200d8)
![image](https://github.com/mlundine/Shoreline_Extraction_GAN/assets/112917719/2d5e9be1-bf88-45e1-848e-8f297eee33c0).

Hope I can get your response soon. 
Best Regards,
Hoang.

**Comment by Donald1983** [comment]
I am very impressive with your model on coastline extraction. I try to run your model but i'm stuck in this step.


![Untitled](https://github.com/mlundine/Shoreline_Extraction_GAN/assets/150317497/d416ead8-0f71-41c1-8536-380127ac1dbb)
(C:\ProgramData\anaconda3) c:\>cd c:\shoreline_extraction_gan
(C:\ProgramData\anaconda3) c:\Shoreline_Extraction_GAN>conda activate shoreline_gan
(shoreline_gan) c:\Shoreline_Extraction_GAN>conda activate shoreline_gan
(shoreline_gan) c:\Shoreline_Extraction_GAN>python shoreline_gan_gui.py
Traceback (most recent call last):
  File "shoreline_gan_gui.py", line 18, in <module>
    from utils import download_utils
  File "c:\Shoreline_Extraction_GAN\utils\download_utils.py", line 11, in <module>
    import SDS_download, SDS_preprocess2
  File "c:\Shoreline_Extraction_GAN\utils\coastsat\SDS_download.py", line 15, in <module>
    import ee
  File "C:\Users\trungnx\.conda\envs\shoreline_gan\lib\site-packages\ee\__init__.py", line 16, in <module>
    from ee import _cloud_api_utils
  File "C:\Users\trungnx\.conda\envs\shoreline_gan\lib\site-packages\ee\_cloud_api_utils.py", line 15, in <module>
    from typing import Any, Callable, Dict, List, Optional, Protocol, Sequence, Tuple, Type, Union
ImportError: cannot import name 'Protocol' from 'typing' (C:\Users\trungnx\.conda\envs\shoreline_gan\lib\typing.py)
(shoreline_gan) c:\Shoreline_Extraction_GAN>

Thank you so much for your model.
Hope to see response soon.
Best Regards,
Trung.

**Comment by jobthoma97** [comment]
> Your model makes me impressive and I try to run our model. So I have 2 questions:
> 
> 1. I also make a shapefile for my case study area but I can't download images by that shapefile. So, I use coordinate as your guidance.
> 2. I get disconnected from the model When I run the shoreline Extraction tool while setting up my data as your guidance.
> 
> ![image](https://private-user-images.githubusercontent.com/112917719/275717563-98277c55-601c-4739-bd7f-b417186200d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyODg1MTcsIm5iZiI6MTcwNzI4ODIxNywicGF0aCI6Ii8xMTI5MTc3MTkvMjc1NzE3NTYzLTk4Mjc3YzU1LTYwMWMtNDczOS1iZDdmLWI0MTcxODYyMDBkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwNjQzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjVhZDg2N2E3ZTk3MDQxYWM3YWU1YWNhNGJjYzk1N2RjZWQzMmM3Y2UyMzY5ZGEzODA2MmQ3Y2NjMjE0YzdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C4LSL6w1B9VvLnfdtDqxhI304QpMiiA2lZLszJu7odQ) ![image](https://private-user-images.githubusercontent.com/112917719/275717315-2d5e9be1-bf88-45e1-848e-8f297eee33c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyODg1MTcsIm5iZiI6MTcwNzI4ODIxNywicGF0aCI6Ii8xMTI5MTc3MTkvMjc1NzE3MzE1LTJkNWU5YmUxLWJmODgtNDVlMS04NDhlLThmMjk3ZWVlMzNjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwNjQzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjA3ODlkODhiMDM2ZjgzMjg0NzBmYzZmNjJmNTUxNzA4YTA0YmQwYmI5ODA5YzVhZjdjMjE5YjhkMjdlMzg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.084WHPMrU2iw1XHiWEqLFF3CfKD_fobZP_nl_gqixEw).
> 
> Hope I can get your response soon. Best Regards, Hoang.

Hello there @VuHoangDao  !!!

I'm also facing the same error as you. Were you able to resolve the error.
Regards,
Job Thomas.

**Comment by dheejaysantos15** [comment]
Hello @VuHoangDao , @Donald1983 and @mlundine . I encounter  similar error when I'm doing this part. I would like to ask if you have fixed this error on your end? If so, do you have any steps or ways to resolve this error. Appreciate your help or response on this. 

Thank you.

Regards, 
David
